### ISSUE TITLE
Docker如何启用GPU加速

### ISSUE THREAD

**Issue by RyaoChengfeng** [Artrajz/vits-simple-api#51]
我尝试了如下的配置
```yaml
version: '3.4'
services:
  vits:
    image: vits-simple-api:latest
    restart: always
    ports:
      - 23456:23456
    environment:
      LANG: 'C.UTF-8'
      TZ: Asia/Shanghai #timezone
    volumes:
      - ./Model:/app/Model # 挂载模型文件夹
      - ./config.py:/app/config.py # 挂载配置文件
      - /opt/cuda:/opt/cuda
      - ./cuda_test.py:/app/cuda_test.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu,utility ]
```
但是torch.cuda.is_available()是False。

nvidia-smi是可用的。

我在Dockerfile中删去了`RUN pip install torch --index-url https://download.pytorch.org/whl/cpu`改为了`RUN pip install torch`.

之后我在容器中将cuda添加到PATH中，使得nvcc -v也可用，但是还是没有解决问题。
